# Begin the story for the user 
print("Welcome to the land of Daggerford a small town of honest blue collar folk: ")
print()
print("But alas something not right in our small town there is a unfamilar sense in the air: ")
print()
print("No one knows what is the cause of this feeling but there isn't time to deal with that now: ")
print()
print("Tragedy has befallen the local Jarl daughter has gone missing!: ")
print()
print("The fisherman's poles have been vandalized!: ")
print()
print("And lastly the local merchant's wares have gone dry!: ")
print()
print("These 3 tragedy has bewitched the town's spirits, 'We are cursed the townsfolk cried' ")
print()
print("One man shouts to the heavens above 'OH GODS IS THERE A CHAMPION AMONG US!!?'")
print()
print("The town spotter looks  outward away from the town and shouts 'LOOK THERE IS SOMEONE APPROACHING THE TOWN!!'")
print()
print("You walk into town square dazed and confused as to why everyone is looking you in such astonishment") 
print()
print("slowly due the townsfolk blocking your path you sauder over to townsquare and then you are approached by the Jarl himself")
print()
print("The Jarl dismisses you entirely exclaiming 'BEGONE LOCAL TRAVELER DAGGERFORD IS CLOSED FOR TRADING AS OF RIGHT NOW!!'")
print()
print("You ask him why and he explains 'Ah my Daughter... the fairest maiden in the whole land of Daggerford is lost that is all I'll speak on the matter right now ")
print()
print("Then the fisherman chimes in 'all my fishing lines have been destroyed we have no fish for trade as well' ")
print()
print("The Jarl in confusment 'WHAT!!? is this true fisherman? '")
print()
print("The fisherman replys sadly 'I'm afraid so my lord...''")
print()
print("The merchant then speaks adding 'Aye and my wares are barren my lord...'") 
print()
print("The Jarl shakes his head in disbelief and says 'what has befallen my kingdom...'")
print()
print("You stand tall in the middle of town square and shout 'I Am A Hero!! I shall take on only one of these tasks but only one '")
print()
print("The 3 men stand up and the Jarl steps forward to say sarcastically 'ok Mr/Mrs.Hero we have 3 problems right here why don't you pick one and make yourself useful'") 
print()
#Prompt user to choose who they would help 
print("Which person would you like to aid?: ")
print()
print("A: The Jarl, who's daughter is missing  ")
print()
print("B: The fisherman, who's poles has been broken ")
print()
print("C: The merchant, who's wares have run dry ")
print()
help = input("Enter who you will aid:'A - C' ") 
print("===================")
#If the user helps the Jarl 
if(help == "A"):
  print("The Jarl says that his daughter most likely lost somewhere in the forest. ") 
  print()
  print("You choose to look for the Jarl's daughter in:'A - C' ")
  print()
  print("A: in the forest: ")
  print()
  print("B: in the mountain: ")
  print()
  print("C: in the cave: ")
  print()
  seaRch = input("Enter where you would like look A-C: ").capitalize()
  #If the user selects "a" 
  if "A" == seaRch:
    print("A: in the forest: ")
    print()
    print("You look in the forest and find the Jarl's daughter held captive by bandits, you kill the bandits and return back to Daggerford with the Jarl's daughter ")
    print()
    print("The Jarl welcomes you back with open arms and in response of your actions The Jarl deems you the new lord   of the land and you marry his daughter and live happliy ever after")
    print()
    print("~~The End~~")
  #If the user selects "b" 
  elif "B" == seaRch:
    print("b: in the mountain: ")
    print()
    print("You look up the mountain and find a flock of crows that charge at you causing you to fall off the mountain and       died in the fall: ")
    print()
    print("~~The End~~")
    print()
    print("You should've listen to the Jarl's advice and checked the forest: ")
  #If the user selects "c"
  elif "C" == seaRch:
    print("c: in the cave")
    print()
    print("You decide to search in the nearby cave and happen to stumble upon a bear unfortunately you are mauled in the process and dies: ")
    print()
    print("~~The End~~") 
    print()
    print("You should've listen to the Jarl's advice and checked the forest: ") 
    print("=================================")
#If the user helps the Fisherman 
elif (help == "B"): 
  print("The Fisherman explains to you that the poles and lines of strings both have to be precise measurements:  ")
  print()
  print("He asked you to solve this equation: ") 
  print()
  print("Y = 3 + 6: " ) 
  print()
  print("What is the answer to the equation?: ") 
  print()
  answer = input("Enter you answer to the equation: ")
  #If the equation is true
  if answer == "9" :
    print()
    print("Great job Hero we have fixed my fishing poles Daggerford is saved let's go catch some fish!!! ")
    print()
    print("~~The End~~")
    #If the equation is false 
  else :
   print()
   print("Oh by the Gods Hero you have dooded us all!!!: ")
   print()
   print("~~The End~~")
   print()
   print("You need to answer the equation correctly: ")
  #If the user helps the Merchant
elif help == "C": 
  print("The Merchant explains the ware's inventory has to be logged to help keep track what each shipment carries and each shipments is at least 100 items:  ")
  print()
  print("The Merchant has two big selling items being fruits and vegetables that need to be logged: ") 
  print()
  #Determine the values of both fruits and vegetables
  frUits =int(input("Enter the amount of fruit you want to order: ")) 
  vegetAbles = int(input("Enter the amount of vegetables you want to order: "))
  print()
  #If the values are greater or equal to 100
  if frUits+vegetAbles >= 100:
    print()
    print("Well done Hero you have helped me restock my wares we are saved!: ")
    print()
    print("~~The End~~") 
  #If the values are less than 100
  else: 
    print()
    print("Oh no Hero!! that wasn't the right amount and that was my only log the wares we are doomed!!!!: ")
    print()
    print("~~The End~~")
    print()
    print("You need to make the Merchant's log larger than a certain amount: ")