# Begin the story for the user 
print("Welcome to the land of Daggerford a small town of honest blue collar folk: ")
print("But alas something not right in our small town there is a unfamilar sense in the air: ")
print("No one knows what is the cause of this feeling but there isn't time to deal with that now: ")
print("Tragedy has befallen the local Jarl daughter has gone missing!: ")
print("The fisherman's poles have been vandalized!: ")
print("And lastly the local merchant's wares have gone dry!: ")
print("These 3 tragedy has bewitched the town's spirits, 'We are cursed the townsfolk cried' ")
print("One man shouts to the heavens above 'OH GODS IS THERE A CHAMPION AMONG US!!?'")
print("The town spotter looks  outward away from the town and shouts 'LOOK THERE IS SOMEONE APPROACHING THE TOWN!!'")
print("You walk into town square dazed and confused as to why everyone is looking you in such astonishment") 
print("slowly due the townsfolk blocking your path you sauder over to townsquare and then you are approached by the Jarl himself")
print("The Jarl dismisses you entirely exclaiming 'BEGONE LOCAL TRAVELER DAGGERFORD IS CLOSED FOR TRADING AS OF RIGHT NOW!!'")
print("You ask him why and he explains")